language: python
sudo: false
cache: pip
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35-dj2.2-sqlite3
    - python: "3.6"
      env: TOXENV=py36-dj2.2-sqlite3
    - python: "3.6"
      env: TOXENV=py36-dj3.0-sqlite3
    - python: "3.6"
      env: TOXENV=py36-dj3.1-sqlite3
    - python: "3.7"
      env: TOXENV=py37-dj2.2-sqlite3
    - python: "3.7"
      env: TOXENV=py37-dj3.0-sqlite3
    - python: "3.7"
      env: TOXENV=py37-dj3.1-sqlite3
    - python: "3.8"
      env: TOXENV=py38-dj2.2-sqlite3
    - python: "3.8"
      env: TOXENV=py38-dj3.0-sqlite3
    - python: "3.8"
      env: TOXENV=py38-dj3.1-sqlite3
    - python: "3.6"
      env: TOXENV=cov
    - python: "3.6"
      env: TOXENV=py36-dj2.2-postgresql9
      services:
        - docker
    - python: "3.6"
      env: TOXENV=py36-dj2.2-postgresql10
      services:
        - docker
    - python: "3.6"
      env: TOXENV=py36-dj2.2-postgresql11
      services:
        - docker
    - python: "3.6"
      env: TOXENV=py36-dj2.2-postgresql12
      services:
        - docker
    - python: "3.6"
      env: TOXENV=py36-dj2.2-mysql8.0
      services:
        - docker
    - python: "3.6"
      env: TOXENV=py36-dj2.2-mssql17
      services:
        - docker
    - python: "3.6"
      env: TOXENV=py36-dj2.2-mssql19
      services:
        - docker

install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
  - sudo apt-get update
  - sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 g++ unixodbc-dev
  - pip install tox-travis
  - pip install tox-docker
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
