language: python
sudo: false
cache: pip
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-dj1.11-sqlite3
    - python: "3.4"
      env: TOXENV=py34-dj1.11-sqlite3
    - python: "3.5"
      env: TOXENV=py35-dj1.11-sqlite3
    - python: "3.5"
      env: TOXENV=py35-dj2.0-sqlite3
    - python: "3.5"
      env: TOXENV=py35-dj2.1-sqlite3
    - python: "3.5"
      env: TOXENV=py35-dj2.2-sqlite3
    - python: "3.6"
      env: TOXENV=py36-dj1.11-sqlite3
    - python: "3.6"
      env: TOXENV=py36-dj2.0-sqlite3
    - python: "3.6"
      env: TOXENV=py36-dj2.1-sqlite3
    - python: "3.6"
      env: TOXENV=py36-dj2.2-sqlite3
    - python: "3.6"
      env: TOXENV=cov
    - python: "3.6"
      env: TOXENV=py36-dj2.2-postgresql9
      services:
        - docker
    - python: "3.6"
      env: TOXENV=py36-dj2.2-postgresql10
      services:
        - docker
    - python: "3.6"
      env: TOXENV=py36-dj2.2-postgresql11
      services:
        - docker
    - python: "3.6"
      env: TOXENV=py36-dj2.2-postgresql12
      services:
        - docker
    - python: "3.6"
      env: TOXENV=py36-dj2.2-mysql8.0
      services:
        - docker
install:
  - pip install tox-travis
  - pip install tox-docker
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls