language: python
sudo: false
cache: pip
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-dj1.11
    - python: "3.4"
      env: TOXENV=py34-dj1.11
    - python: "3.5"
      env: TOXENV=py35-dj1.11
    - python: "3.5"
      env: TOXENV=py35-dj2.0
    - python: "3.5"
      env: TOXENV=py35-dj2.1
    - python: "3.5"
      env: TOXENV=py35-dj2.2
    - python: "3.6"
      env: TOXENV=py36-dj1.11
    - python: "3.6"
      env: TOXENV=py36-dj2.0
    - python: "3.6"
      env: TOXENV=py36-dj2.1
    - python: "3.6"
      env: TOXENV=py36-dj2.2
    - python: "3.6"
      env: TOXENV=cov
install:
  - pip install tox-travis
  - pip install tox-docker
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls